apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: backend-service
          image: gagankshetty/arxiv-insanity:backend-service
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-service-secrets
                  key: JWT_SECRET
                  optional: false
            - name: OAUTH2_CLIENT_ID
              valueFrom:
                  secretKeyRef:
                    name: backend-service-secrets
                    key: OAUTH2_CLIENT_ID
                    optional: false
            - name: OAUTH2_SECRET
              valueFrom:
                  secretKeyRef:
                    name: backend-service-secrets
                    key: OAUTH2_SECRET
                    optional: false
            - name: OAUTH2_REDIRECT_URL
              valueFrom:
                  secretKeyRef:
                    name: backend-service-secrets
                    key: OAUTH2_REDIRECT_URL
                    optional: false