package auth

const USER_SESSION = "USER_SESSION"
const REDIRECT_URL = "REDIRECT_URL"
const JWT_SECRET = "JWT_SECRET"
const OAUTH2_CLIENT_ID = "OAUTH2_CLIENT_ID"
const OAUTH2_SECRET = "OAUTH2_SECRET"
const OAUTH2_REDIRECT_URL = "OAUTH2_REDIRECT_URL"
