package auth

const COOKIE_KEY = "USER_SESSION"
const JWT_SECRET = "JWT_SECRET"
const OAUTH2_CLIENT_ID = "OAUTH2_CLIENT_ID"
const OAUTH2_SECRET = "OAUTH2_SECRET"
const OAUTH2_REDIRECT_URL = "OAUTH2_REDIRECT_URL"
