# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to GKE

on:
  workflow_dispatch:
    inputs:
      build:
        type: boolean
        description: Rebuild the docker image?
      deploy:
        type: boolean
        description: Deploy the application on GKE?

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
  GCP_SA_CREDENTIALS: ${{ secrets.GCP_SA_CREDENTIALS}}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}    # Add your cluster name here.
  GKE_ZONE: ${{ vars.GKE_ZONE }}   # Add your cluster zone here.
  IMAGE_TAG: arxiv-insanity:backend-service

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

      # Login to docker hub
    - name: docker login
      if: ${{inputs.build}}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS 

    # Setup the buildx to build the docker image
    - name: Set up Docker Buildx
      if: ${{inputs.build}}
      uses: docker/setup-buildx-action@v2

    # Build and push the docker image
    - name: Build the Docker image
      if: ${{inputs.build}}
      run: docker buildx build --file ./Dockerfile --platform=linux/arm64,linux/amd64 --tag $DOCKERHUB_USER/$IMAGE_TAG --output type=image,push=true .

    - id: 'auth'
      if: ${{inputs.deploy}}
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ env.GCP_SA_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      if: ${{inputs.deploy}}
      uses: 'google-github-actions/setup-gcloud@v1'

    - id: 'get-credentials'
      if: ${{inputs.deploy}}
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Deploy secret
      if: ${{inputs.deploy}}
      env: 
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        OAUTH2_CLIENT_ID: ${{ secrets.OAUTH2_CLIENT_ID }}
        OAUTH2_SECRET: ${{ secrets.OAUTH2_SECRET }}
        OAUTH2_REDIRECT_URL: ${{ secrets.OAUTH2_REDIRECT_URL }}
        SECRET_NAME: "backend-service-secrets"
      run: |-
        kubectl delete secret $SECRET_NAME --ignore-not-found=true
        kubectl create secret generic $SECRET_NAME --from-literal=JWT_SECRET=$JWT_SECRET --from-literal=OAUTH2_CLIENT_ID=$OAUTH2_CLIENT_ID --from-literal=OAUTH2_SECRET=$OAUTH2_SECRET --from-literal=OAUTH2_REDIRECT_URL=$OAUTH2_REDIRECT_URL
        kubectl get secrets -o wide

    # Deploy the Docker image to the GKE cluster
    - name: Deploy app
      if: ${{inputs.deploy}}
      run: |-
        kubectl apply -f ./kubernetes
        kubectl get services -o wide
        kubectl get pods -o wide