# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to GKE

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
  GCP_SA_CREDENTIALS: ${{ secrets.GCP_SA_CREDENTIALS}}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}    # Add your cluster name here.
  GKE_ZONE: ${{ vars.GKE_ZONE }}   # Add your cluster zone here.
  IMAGE_TAG: arxiv-insanity:backend-service

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    # - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
    #   with:
    #     service_account_key: ${{ env.GCP_SA_CREDENTIALS }}
    #     project_id: ${{ env.PROJECT_ID }}
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ env.GCP_SA_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Get the GKE credentials so we can deploy to the cluster
    # - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
    #   with:
    #     cluster_name: ${{ env.GKE_CLUSTER }}
    #     location: ${{ env.GKE_ZONE }}
    #     credentials: ${{ env.GCP_SA_CREDENTIALS }}

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
    # Login to docker hub
    - name: docker login
      # env:
      #   DOCKERHUB_USER: ${{ env.DOCKERHUB_USER }}
      #   DOCKERHUB_PASS: ${{ env.DOCKERHUB_PASS }}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS 
    # Setup the buildx to build the docker image
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    # Build and push the docker image
    - name: Build the Docker image
      run: docker buildx build --file ./Dockerfile --platform=linux/arm64,linux/amd64 --tag $DOCKERHUB_USER/$IMAGE_TAG --output type=image,push=true .
      

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f ./kubernetes
        kubectl get services -o wide
        kubectl get pods -o wide